### ISSUE TITLE
Doesn't work for packages that are not on Hackage?

### ISSUE THREAD

**Issue by osa1** [vincenthz/cabal-db#9]
I don't know how is `cabal-db` working, but as far as I can see it's not working for packages that are not on Hackage.

I have a library and executable that I develop using sandbox so every dependency is in the sandbox or in system-level dirs. Is there a way to make `cabal-db` working in this case? Would it be too hard to add this feature?

**Comment by freeman42x** [comment]
:+1: Would be really useful to have, was just about to ask the same question.

**Comment by creswick** [comment]
A nice middle ground would be to accept a .cabal file instead of a package name, and just add that to the db, then query on the (extracted) package name.

That wouldn't help for the situation where you have multiple packages that are locally-hosted, but it would allow you to run cabal-db queries against a package that you have not yet released (or one that you just added dependencies to, and want to see a dependency graph for, because it just stopped building... ;)

**Comment by ntc2** [comment]
Another vote for supported dependency graphing for local packages. I'm trying to make sense of the dependencies of an internal package at work that will never end up on Hackage.

**Comment by ntc2** [comment]
And for anyone else ending up here, Stack has a `stack dot` command that supports local packages and pruning: https://docs.haskellstack.org/en/stable/dependency_visualization/.

**Comment by vincenthz** [comment]
It's very unlikely i'll update cabal-db now, and I'll just probably try to merge whatever is missing into stack itself if I get to it.
